version: '3.6'
services:
  #Nginx Service for load balance 
  main-service-gw:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    tty: true
    volumes:
      - ./.:/node/src
#     networks:
#       - app-network
# networks:
#   app-network:
#     driver: bridge
